### ISSUE TITLE
Alternate two groups of Bubble Push Fields through a Core-like switch

### ISSUE THREAD

**Issue by max4805** [EverestAPI/SpringCollab2020#102]
Be able to have 2 groups of bubble push fields, that alternate when hitting a switch behaving much like a core toggle.

itsabrody provided sprites for their request: [BubbleColumnSwitch.zip](https://cdn.discordapp.com/attachments/663508177181999136/676347288318377994/BubbleColumnSwitch.zip).

_Requested by itsabrody#4950_

**Comment by Cruor** [comment]
Would it be sane to just add  `flag` and `inverted` attributes to the bubble field and control it like that?

**Comment by max4805** [comment]
Yes, I think that would get this request covered and allow to use any of the flag-controlling entities out there. Plus, there already is a "core toggle controlling flags instead" planned for #76, so this could be reused.

**Comment by max4805** [comment]
@Cruor assigning you as well since you are planning to work on the core switch (both for this request and for #76).

**Comment by max4805** [comment]
Core-like flag switch done in Pandora's Box
