### ISSUE TITLE
Missing tooltips for Glass Berry and Return Berry

### ISSUE THREAD

**Issue by Cruor** [EverestAPI/SpringCollab2020#107]
Following tooltips are missing, didn't catch that when approving.

SpringCollab2020/returnBerry
*    winged
*    order
*    checkpointID

SpringCollab2020/glassBerry
*    order
*    checkpointID

**Comment by max4805** [comment]
Missing tooltips for Lightning Dash Switch as well:
SpringCollab2020/LightningDashSwitch
   * side
   * sprite
   * persistent

**Comment by WoofWoofDoggo** [comment]
https://gist.github.com/WoofWoofDoggo/25b67bc6b2073e68669de7c26b560604

Before making another slew of commits to resolve this issue, do these tooltips look fine? @Cruor

**Comment by Cruor** [comment]
Looks good to me @WoofWoofDoggo
