### ISSUE TITLE
Water drowning mechanic + Air refills

### ISSUE THREAD

**Issue by max4805** [EverestAPI/SpringCollab2020#19]
> A new type of water that maddy can drown in if under for too long. Have an oxygen meter that basically behaves the exact same way as stamina only killing you and instead of whilst climbing of course whilst submerged in water. Also would be nice to have a refill specific for replenishing air.

Visually, running out of oxygen would look exactly like running out of stamina (Madeline blinks red). A water bubble looking sprite will be provided for the air refill.

_Requested on collabcord_

**Comment by Cruor** [comment]
Added to Pandora's Box in 1.0.10
https://gamebanana.com/updates/48869
