### ISSUE TITLE
Multi-directional jumpthrus

### ISSUE THREAD

**Issue by max4805** [EverestAPI/SpringCollab2020#20]
> multi-directional jumpthru's, they'd be able to use any jumpthru tileset and just rotate it hopefully

_Requested by RadleyMcTuneston on collabcord._

**Comment by max4805** [comment]
Unassigning myself since PenguinOwl grabbed that task. I'll keep my (little) progress in case this is needed.

**Comment by PenguinOwl** [comment]
@max4805 by all means keep working on this, I am not doing this as my main task

**Comment by max4805** [comment]
Moving that back into In progress since I already have pieces of code for it.

**Comment by max4805** [comment]
Progress report: I got an upside-down jumpthru that blocks Madeline if she hits it from the bottom. It looks weird because of Madeline's hitbox though. The rendering of it is also still broken (I tried to mirror the jumpthru sprite in code but it somehow went wrong).

**Comment by max4805** [comment]
Upide-down part done in #54!
