### ISSUE TITLE
Plus One Dash refill for inventories with Two Dashes

### ISSUE THREAD

**Issue by PenguinOwl** [EverestAPI/SpringCollab2020#33]
> Can someone make an item for Radeline, that's like a dash refresher but only gives back 1 dash?

*Requested by SilverStar#9784*

**Comment by GreyMario** [comment]
I've renamed this request to better reflect the content. It's meant to add one dash to the current number of available dashes; no dashes -> one dash, one dash -> two dashes, capping at the inventory dash max.

**Comment by JaThePlayer** [comment]
Added to Frost Helper 1.9 https://gamebanana.com/gamefiles/9201
