### ISSUE TITLE
No Dash area

### ISSUE THREAD

**Issue by PenguinOwl** [EverestAPI/SpringCollab2020#36]
> A red field entity that you can't dash inside. You will keep your dash/refill but can't use it until you leave it. It'll have red particles and a heatwave effect. If you press the dash key inside, it'll do nothing. Also it can move like Space Jam.

*Requested by DomGames#4148*

**Comment by JaThePlayer** [comment]
Added to Frost Helper 1.8 https://gamebanana.com/gamefiles/9201
