### ISSUE TITLE
Dashing spinner

### ISSUE THREAD

**Issue by PenguinOwl** [EverestAPI/SpringCollab2020#38]
> idea number two: A codemod that allows you to dash through a specific type of spinner, as in you just go right through it invincibility style. If you don't dash, however, you die. also a @Spriter request actually for a sort of translucid spinner if a modder is available

*Requested by SC | [SC] Hydro0#4059*

**Comment by GreyMario** [comment]
This idea was partially handled as a Dream Spinner, curiously enough. Isa's Grab Bag has them. I'll give them a quick poke, see if they'd like to implement this for us.

**Comment by JaThePlayer** [comment]
Added to Frost Helper 1.7.1 https://gamebanana.com/gamefiles/9201
