### ISSUE TITLE
More touch switch customization

### ISSUE THREAD

**Issue by GreyMario** [EverestAPI/SpringCollab2020#49]
Basically, touch switches that can set arbitrary session flags, allowing the triggered object to be in potentially any room and removing the need for a maximum of one set of touch switches/triggered objects per room.

Additionally, the same variant for *moving* and *timed* switches as seen in Outback Helper.

*Requested by Oppen_heimer#9999*

**Comment by BLimmie** [comment]
To add, it would be nice to have the option to color each group a certain color for clarity in designing levels.

-Oppen_heimer

**Comment by GreyMario** [comment]
For colorblind-friendliness I asked for different *shapes* to use inside touch switches; as a result, we've received [this pack of three additional icon suggestions](https://cdn.discordapp.com/attachments/663507475324076045/670551878366527508/touchSwitches.zip) which can be used to help conceptually "group" switches.

**Comment by max4805** [comment]
> Additionally, the same variant for moving and timed switches as seen in Outback Helper.

This part of the request was abandoned. This means #81 will close this issue.
