### ISSUE TITLE
More variants on Rising Lava

### ISSUE THREAD

**Issue by GreyMario** [EverestAPI/SpringCollab2020#51]
Let's mash together some ideas into one feature request.

- [ ] *Reversed* vertical lava/ice that comes from the top instead of the bottom.
- [ ] ~*Backward* vertical lava/ice that descends from near the top of the room.~ no maybe this is silly
- [x] Sandwich lava that plays nicely with vertical rooms, and with customizable height.
- [x] Sandwich lava that changes type, but not direction, when core mode is changed.
  - [x] Reverse-direction of the above.
- [x] Horizontally moving "rising lava".
- [x] Horizontally moving sandwich lava.

[Edit by max480] Extra idea that could be neat even if not requested by a mapper:
- [ ] Be able to trigger lava using a session flag.

**Comment by max4805** [comment]
I'll grab "sideways lava" requests first ("horizontal moving rising lava" and "horizontal moving sandwich lava").

**Comment by max4805** [comment]
:arrow_up: This PR addresses the 2 last bullets in the list.
Idea from Natalie I'll add here: be able to make lava attack only if a certain session flag is set.

**Comment by max4805** [comment]
Since this is a multi-request, I turned the original comment into a checklist, and I'll be sure to check things as I do them.

**Comment by max4805** [comment]
"One-way sandwich lava" and "sandwich lava playing nicely with vertical rooms" are pretty much done, except the customizable height part. They will come in an entity very creatively named "custom sandwich lava".

**Comment by max4805** [comment]
Moving that back to To do, as I'm shifting to other stuff. Things checked in the description are done.

**Comment by max4805** [comment]
After some discussion, it seems like remaining tasks are not mapper-requested. Closing the issue.
