### ISSUE TITLE
"Troll" berry which just pops when "collected"

### ISSUE THREAD

**Issue by GreyMario** [EverestAPI/SpringCollab2020#52]
...yeah.

*Requested by SilverStar#9784*

**Comment by GreyMario** [comment]
I'll knock this one out.. uh.. tomorrow, if I'm not busy.

**Comment by GreyMario** [comment]
Self-unassigning, since I'm in a terrible position to do this right now.

Remember that the "troll berry" isn't really a berry, and as such you can't *register* it as one, because that would add an unclaimable berry to the total possible berries.

Yell at me if you think you can make a case for implementing "super secret" registered berries (doesn't add to the Maximum Strawberries in a campaign).

**Comment by max4805** [comment]
... totally agree, the registry shouldn't even consider that as a strawberry. It is not even a secret untracked one, since it can't be collected.
