### ISSUE TITLE
More variations on the Bird tutorial

### ISSUE THREAD

**Issue by max4805** [EverestAPI/SpringCollab2020#60]
The following variations of the Tutorial bird have been requested on Collabcord:
- Reverse super
- Wavedash and Reverse wavedash (requested by DanTKO; abandoned)
- Fast falling (requested by DanTKO)

Can evolve into "customizable bird tutorial". In this case, this will be candidate for integration into Everest instead.

**Comment by Cruor** [comment]
DanTKO no longer needs this.
Keeping the issue open, some one else might need it, and the customization part seems like a good Everest addition.
