### ISSUE TITLE
Cavern Helper improvement: Crystal Bomb detonation field

### ISSUE THREAD

**Issue by GreyMario** [EverestAPI/SpringCollab2020#62]
A "seeker barrier"-like field that auto-detonates Crystal Bombs when they enter its area of effect.

This should be absolutely trivial to implement on our end, even *with* whatever hacks we may need to make sure we're not breaking things when Cavern Helper isn't around, but I'm going to poke Exudias to see if we can get it snuck into Cavern Helper proper first.

*Requested by iamdadbod*

**Comment by GreyMario** [comment]
Another user has requested that this be expanded to all carryables. Personal note: is a squish callback a universally used thing among carryables? It'll be tricky otherwise...

**Comment by GreyMario** [comment]
So much for "trivial"; if we don't want to use the standard "remove self" routine (which we really don't want to do for most things), we'll need to temporarily create a new Solid to fully cover the object being destroyed, then pass it as part of an arbitrary CollisionData to the Actor's OnSquish...

**Comment by GreyMario** [comment]
The *bomb detonator* is complete, but nothing has been created to kill other carryables.

**Comment by max4805** [comment]
> Another user has requested that this be expanded to all carryables.
This was a misunderstanding (the requester wanted the throwable to break the barrier instead), this part of the request is abandoned.
