### ISSUE TITLE
Disable Ice Physics Trigger

### ISSUE THREAD

**Issue by max4805** [EverestAPI/SpringCollab2020#75]
A trigger that disables ice physics when the core mode is in ice. Would make mappers able to build levels with Ice mode stuff (change in colour, change in sandwich lava direction) without the ice physics being implemented. This would mean disable that part of the code:
```cs
if (this.onGround && this.level.CoreMode == Session.CoreModes.Cold) {
   num *= 0.3f;
}
```

_Requested by dahlukeh#3909_

**Comment by GreyMario** [comment]
Personal notes:

- `CoreModes.Cold` only appears once in Player.cs
- We could accomplish this on the Everest side by implementing a metadata flag, but that's for later on down the road, perhaps.
- For now, it's likely that we can hack in a call that checks the Level for the existence of a special controller (which is placed in the intro room and therefore loaded at the beginning of the stage).

**Comment by max4805** [comment]
What I had in my head for that is a trigger that changes a flag in the mod session, and a hook that checks for this flag. That's why I put "trigger" in the title. 😅
