### ISSUE TITLE
Reskinnable entities

### ISSUE THREAD

**Issue by max4805** [EverestAPI/SpringCollab2020#99]
The following entities have been requested to be made reskinnable:
- [x] springs (_requested by Cookie 🍪#7766 and hyper <3#2137_)
- [x] refills (_requested by ChrisMcCrazy#0144_): also make the particle color changeable (_requested by hyper <3#2137_)

**Comment by JaThePlayer** [comment]
Custom Springs added to Frost Helper 1.14 https://gamebanana.com/gamefiles/9201
Frost Helper's Plus One Refills can be retextured and particle color can be changed. If used correctly they work exactly the same way as regular refills, so that request is fullfilled too.
